/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversortemperaturas.ui;

import com.mycompany.conversortemperaturas.utils.ConversorLogica;

/**
 *
 * @author Gregory
 */
public class ConversorFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConversorFrame.class.getName());

    /**
     * Creates new form ConversorFrame
     */
    public ConversorFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_tipo_conversion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bt_calcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        tf_valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_respuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        cb_tipo_conversion.setBackground(new java.awt.Color(102, 102, 102));
        cb_tipo_conversion.setForeground(new java.awt.Color(255, 255, 255));
        cb_tipo_conversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius a Fahrenheit", "Fahrenheit a Celsius", "Celsius a Kelvin", "Kelvin a Celsius", "Fahrenheit a Kelvin", "Kelvin a Fahrenheit" }));
        cb_tipo_conversion.addActionListener(this::cb_tipo_conversionActionPerformed);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conversor de Temperaturas en Java con Swing");
        jLabel1.setToolTipText("fgfg");

        bt_calcular.setBackground(new java.awt.Color(0, 153, 0));
        bt_calcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_calcular.setForeground(new java.awt.Color(51, 51, 51));
        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(this::bt_calcularActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GRUPO # 2");
        jLabel2.setToolTipText("fgfg");

        bt_salir.setBackground(new java.awt.Color(255, 0, 0));
        bt_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_salir.setForeground(new java.awt.Color(255, 255, 255));
        bt_salir.setText("X");
        bt_salir.addActionListener(this::bt_salirActionPerformed);

        bt_limpiar.setBackground(new java.awt.Color(204, 153, 0));
        bt_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_limpiar.setForeground(new java.awt.Color(51, 51, 51));
        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(this::bt_limpiarActionPerformed);

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_valorKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Valor a Convertir");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccione la Coversion deseada");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resultado");

        lb_respuesta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lb_respuesta.setForeground(new java.awt.Color(255, 255, 255));
        lb_respuesta.setText("Respuesta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_valor)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_respuesta)
                            .addComponent(jLabel5))
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_calcular)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt_limpiar))
                                    .addComponent(jLabel4)
                                    .addComponent(cb_tipo_conversion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(111, 111, 111)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_salir)))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bt_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_tipo_conversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(lb_respuesta)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_calcular)
                            .addComponent(bt_limpiar))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipo_conversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_conversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_conversionActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        String textoIngresado = tf_valor.getText();

        // 1. Validar que no esté vacío
        if (textoIngresado.isEmpty()) {
            // Mostrar alerta al usuario
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor a convertir.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución para que no intente calcular nada
        }

        double valor;

        // 2. Validar que sea un número válido matemáticamente
        try {
            valor = Double.parseDouble(textoIngresado);
        } catch (NumberFormatException e) {
            // Si el usuario pegó letras o un formato inválido, atrapamos el error aquí
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución
        }

        // --- Si el código llega hasta aquí, el número es 100% seguro ---
        String seleccion = (String) cb_tipo_conversion.getSelectedItem();
        
        double res;

        switch (seleccion) {
            case "Celsius a Fahrenheit":
                res = ConversorLogica.celsiusAFahrenheit(valor);
                // %.2f formatea el número a 2 decimales, seguido del símbolo °F
                lb_respuesta.setText(String.format("%.2f °F", res));
                break;
            case "Fahrenheit a Celsius":
                res = ConversorLogica.fahrenheitACelsius(valor);
                lb_respuesta.setText(String.format("%.2f °C", res));
                break;
            case "Celsius a Kelvin":
                res = ConversorLogica.celsiusAKelvin(valor);
                // Recuerda: Kelvin es una escala absoluta, no usa el símbolo "°"
                lb_respuesta.setText(String.format("%.2f K", res));
                break;
            case "Kelvin a Celsius":
                res = ConversorLogica.kelvinACelsius(valor);
                lb_respuesta.setText(String.format("%.2f °C", res));
                break;
            case "Fahrenheit a Kelvin":
                res = ConversorLogica.fahrenheitAKelvin(valor);
                lb_respuesta.setText(String.format("%.2f K", res));
                break;
            case "Kelvin a Fahrenheit":
                res = ConversorLogica.kelvinAFahrenheit(valor);
                lb_respuesta.setText(String.format("%.2f °F", res));
                break;
        }
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        lb_respuesta.setText("Respuesta");
        tf_valor.setText("");
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void tf_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyTyped
        char c = evt.getKeyChar();

        // Suponiendo que tu JTextField se llama tf_valor
        String textoActual = tf_valor.getText();

        // 1. Permitir solo dígitos, el punto y el signo menos
        if (!Character.isDigit(c) && c != '.' && c != '-') {
            evt.consume(); // Ignora cualquier otra letra o símbolo
        }

        // 2. Evitar que se escriba más de un punto decimal
        if (c == '.' && textoActual.contains(".")) {
            evt.consume();
        }

        // 3. (Opcional) Evitar que el signo menos vaya en medio del número
        if (c == '-' && !textoActual.isEmpty()) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_valorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConversorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JComboBox<String> cb_tipo_conversion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_respuesta;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
